export type SeoPage = {
  slug: string;
  title: string;
  description: string;
  h1: string;
  eyebrow: string;
  pain: string;
  solution: string;
  benefits: string[];
  deliverables: string[];
  cta: string;
  priceAnchor?: string;
};

export const services: SeoPage[] = [
  {
    slug: "webs-premium-para-negocios",
    title: "Webs premium para negocios | Andrés Fabián Rendón",
    description: "Diseño y desarrollo de webs premium para negocios locales que quieren captar leads, parecer una marca fuerte y vender más.",
    h1: "Webs premium para negocios que necesitan vender más",
    eyebrow: "Diseño web premium",
    pain: "Tu negocio no necesita otra web bonita que nadie usa: necesita una presencia digital que genere confianza y contactos reales.",
    solution: "Creo webs con estética premium, copywriting comercial, SEO local, CTA claros y estructura preparada para convertir visitas en leads.",
    benefits: ["Diseño visual de alto impacto", "SEO técnico desde la base", "Formulario de captación", "WhatsApp y llamadas integradas", "Mobile-first", "Preparada para escalar a CRM"],
    deliverables: ["Home premium", "Páginas de servicios", "Formulario de leads", "Optimización SEO", "Diseño responsive", "Documentación de entrega"],
    cta: "Solicitar auditoría web gratuita",
    priceAnchor: "Proyectos desde 1.500 € hasta sistemas completos de 15.000 €",
  },
  {
    slug: "automatizacion-con-inteligencia-artificial",
    title: "Automatización con inteligencia artificial para empresas",
    description: "Automatiza respuestas, reservas, seguimiento de leads y procesos comerciales con IA, WhatsApp y CRM.",
    h1: "Automatización con inteligencia artificial para negocios que quieren ahorrar tiempo",
    eyebrow: "IA aplicada a negocio real",
    pain: "Cada lead que no respondes rápido, cada mensaje repetido y cada tarea manual te está costando dinero.",
    solution: "Diseño flujos de automatización con IA para captar, responder, clasificar y dar seguimiento a clientes desde web, WhatsApp y CRM.",
    benefits: ["Respuestas automáticas", "Clasificación de leads", "Seguimientos", "Menos trabajo manual", "Más velocidad comercial", "Integración con herramientas existentes"],
    deliverables: ["Mapa de procesos", "Automatización inicial", "Webhook", "Notificaciones", "Integración CRM", "Manual de uso"],
    cta: "Auditar mi proceso comercial",
  },
  {
    slug: "chatbot-whatsapp-para-empresas",
    title: "Chatbot WhatsApp para empresas y negocios locales",
    description: "Chatbot WhatsApp para responder preguntas, captar datos, enviar precios, agendar citas y derivar al equipo comercial.",
    h1: "Chatbot WhatsApp para convertir conversaciones en clientes",
    eyebrow: "WhatsApp + IA",
    pain: "Tus clientes quieren respuestas rápidas, precios claros y una forma fácil de reservar o pedir información.",
    solution: "Creo asistentes WhatsApp para responder FAQ, enviar enlaces, captar datos y escalar a humano cuando sea necesario.",
    benefits: ["Atención 24/7", "Menos mensajes repetidos", "Más reservas", "Captación de datos", "Escalado a humano", "Seguimiento automático"],
    deliverables: ["Flujo conversacional", "Mensajes base", "Integración webhook", "Formulario de fallback", "Dashboard de leads", "Pruebas de seguridad"],
    cta: "Quiero un chatbot para mi negocio",
  },
  {
    slug: "seo-local-para-negocios",
    title: "SEO local para negocios | Captación en Google",
    description: "SEO local para negocios que quieren aparecer en Google y captar clientes por ciudad, servicio y nicho.",
    h1: "SEO local para que tu negocio aparezca cuando tus clientes buscan",
    eyebrow: "SEO que atrae leads",
    pain: "Si tus clientes buscan en Google y no te encuentran, estás regalando oportunidades a la competencia.",
    solution: "Creo arquitectura SEO, páginas por servicio, páginas locales, contenido útil y optimización técnica para captar tráfico cualificado.",
    benefits: ["Páginas por servicio", "Páginas por ciudad", "Estructura semántica", "Schema", "Sitemap", "Contenido con intención comercial"],
    deliverables: ["Keyword map", "Arquitectura SEO", "Metadata", "Sitemap", "Contenido base", "Plan de publicaciones"],
    cta: "Solicitar diagnóstico SEO",
  },
  {
    slug: "software-saas-para-empresas",
    title: "Software SaaS para empresas | MVPs y sistemas privados",
    description: "Diseño y desarrollo de MVPs SaaS, paneles privados, CRM y sistemas internos para empresas.",
    h1: "Software SaaS para empresas que quieren controlar su operación",
    eyebrow: "SaaS y producto digital",
    pain: "Excel, WhatsApp y herramientas sueltas funcionan al principio, pero luego frenan el crecimiento.",
    solution: "Construyo sistemas web privados con dashboard, roles, base de datos, clientes, métricas y automatizaciones.",
    benefits: ["Dashboard propio", "Base de datos", "Roles", "Métricas", "Automatizaciones", "Escalable a producto SaaS"],
    deliverables: ["Arquitectura", "MVP", "Dashboard", "Auth", "Base de datos", "Deploy"],
    cta: "Diseñar mi sistema SaaS",
  },
  {
    slug: "auditoria-digital-para-negocios",
    title: "Auditoría digital para negocios | Web, SEO, IA y automatización",
    description: "Auditoría digital de web, SEO, Instagram, WhatsApp y oportunidades de automatización para negocios locales.",
    h1: "Auditoría digital para detectar por qué tu negocio no capta más clientes",
    eyebrow: "Diagnóstico comercial",
    pain: "Puede que tengas web, Instagram y WhatsApp, pero sin estrategia clara no sabes qué está fallando.",
    solution: "Reviso tu presencia digital y te entrego un plan claro para mejorar conversión, SEO, automatización y experiencia del cliente.",
    benefits: ["Diagnóstico web", "Revisión SEO", "Análisis WhatsApp", "Ideas de automatización", "Prioridades claras", "Plan de acción"],
    deliverables: ["Informe resumen", "Lista de mejoras", "Mapa de oportunidades", "Prioridad por impacto", "Propuesta de implementación"],
    cta: "Pedir auditoría gratis",
  },
  {
    slug: "crm-para-negocios-locales",
    title: "CRM para negocios locales | Leads, pipeline y seguimiento",
    description: "CRM para negocios locales que quieren ordenar leads, estados, propuestas, seguimientos y oportunidades comerciales.",
    h1: "CRM para negocios locales que no quieren perder ninguna oportunidad",
    eyebrow: "CRM y pipeline",
    pain: "Cuando los leads quedan repartidos entre WhatsApp, Instagram, email y notas, el seguimiento se rompe y las ventas se pierden.",
    solution: "Diseño un CRM visual para centralizar oportunidades, estados, servicios solicitados, valor estimado, próximos pasos y automatizaciones.",
    benefits: ["Pipeline claro", "Estados comerciales", "Seguimientos", "Métricas de conversión", "Valor estimado", "Integración con formularios"],
    deliverables: ["Dashboard CRM", "Tabla de leads", "Estados personalizados", "Métricas", "Notificaciones", "Base Supabase preparada"],
    cta: "Quiero ordenar mis leads",
  },
  {
    slug: "sistemas-de-reservas-para-negocios",
    title: "Sistemas de reservas para negocios | Agenda, WhatsApp y CRM",
    description: "Sistemas de reservas para barberías, restaurantes, clínicas y negocios locales conectados con web, WhatsApp y CRM.",
    h1: "Sistemas de reservas para negocios que necesitan una agenda más ordenada",
    eyebrow: "Reservas y agenda",
    pain: "Las reservas por mensajes manuales generan errores, huecos perdidos, respuestas repetidas y poca visibilidad del negocio.",
    solution: "Construyo sistemas de reservas con agenda, servicios, disponibilidad, confirmaciones, WhatsApp y dashboard de seguimiento.",
    benefits: ["Agenda online", "Menos errores", "Confirmaciones", "QR para el local", "Datos de clientes", "Preparado para automatizar"],
    deliverables: ["Flujo de reserva", "Página de servicios", "Panel visual", "Mensajes", "Integración CRM", "Documentación"],
    cta: "Diseñar mi sistema de reservas",
  },
];

export const niches: SeoPage[] = [
  {
    slug: "web-para-barberias",
    title: "Web para barberías | Reservas, QR y captación",
    description: "Web para barberías con reservas, QR, WhatsApp, SEO local y sistema de captación de clientes.",
    h1: "Web para barberías que convierte visitas en reservas",
    eyebrow: "Barberías",
    pain: "Muchas barberías dependen solo de Instagram y WhatsApp, pero pierden reservas por no tener un sistema claro.",
    solution: "Creo una web con reservas, QR, servicios, barberos, WhatsApp, reseñas y SEO local para llenar mejor la agenda.",
    benefits: ["Reservas online", "QR para el local", "SEO local", "WhatsApp", "Servicios claros", "Diseño premium"],
    deliverables: ["Landing", "Página de reservas", "Servicios", "CTA WhatsApp", "SEO básico", "QR"],
    cta: "Quiero captar más reservas",
  },
  {
    slug: "software-para-barberias",
    title: "Software para barberías | Agenda, caja, clientes y marketing",
    description: "Software para barberías con agenda, caja, clientes, recordatorios, reseñas y marketing inteligente.",
    h1: "Software para barberías que quieren controlar reservas, caja y clientes",
    eyebrow: "BarberíaOS",
    pain: "Sin control de agenda, caja y clientes, el dueño no sabe qué pasa realmente cada día.",
    solution: "Implemento sistemas tipo BarberíaOS para controlar reservas, barberos, servicios, clientes, caja y acciones de marketing.",
    benefits: ["Agenda", "Caja", "Clientes", "Barberos", "Promociones", "Reseñas"],
    deliverables: ["Dashboard", "Agenda", "CRM", "Caja", "Reportes", "Onboarding"],
    cta: "Ver sistema para barberías",
  },
  {
    slug: "web-para-restaurantes",
    title: "Web para restaurantes | Carta digital, pedidos y reservas",
    description: "Web para restaurantes con carta digital, pedidos, reservas, WhatsApp y SEO local.",
    h1: "Web para restaurantes que vende antes de que el cliente llegue",
    eyebrow: "Restaurantes",
    pain: "Si tu carta, reservas y pedidos no son fáciles desde el móvil, el cliente se va a otro sitio.",
    solution: "Creo webs para restaurantes con carta digital, CTA de pedido, reservas, WhatsApp, Google Maps y SEO local.",
    benefits: ["Carta digital", "Pedidos", "Reservas", "WhatsApp", "Google Maps", "SEO local"],
    deliverables: ["Home", "Carta", "Reservas", "CTA pedido", "SEO", "Diseño mobile"],
    cta: "Mejorar mi restaurante online",
  },
  {
    slug: "web-para-pizzerias",
    title: "Web para pizzerías | Carta, pedidos y SEO local",
    description: "Web para pizzerías con carta digital, pedidos por WhatsApp, promociones, Google Maps y SEO local.",
    h1: "Web para pizzerías que convierte búsquedas locales en pedidos",
    eyebrow: "Pizzerías",
    pain: "Si el cliente no encuentra rápido carta, precios, ubicación y forma de pedir, termina comprando en otra pizzería.",
    solution: "Creo una web mobile-first con carta, combos, CTA de pedido, reseñas, ubicación, SEO local y seguimiento de contactos.",
    benefits: ["Carta clara", "Pedidos por WhatsApp", "Promos", "SEO local", "Google Maps", "Más confianza"],
    deliverables: ["Home", "Carta digital", "CTA pedido", "SEO local", "Reseñas", "Analítica"],
    cta: "Mejorar mi pizzería online",
  },
  {
    slug: "web-para-empresas-de-limpieza",
    title: "Web para empresas de limpieza | Leads y presupuestos",
    description: "Web para empresas de limpieza de cristales, final de obra y servicios profesionales con captación de presupuestos.",
    h1: "Web para empresas de limpieza que necesitan más presupuestos",
    eyebrow: "Limpieza profesional",
    pain: "El cliente busca confianza, rapidez y ejemplos antes de pedir presupuesto.",
    solution: "Creo una web con servicios claros, antes/después, zonas de trabajo, formulario de presupuesto y seguimiento de leads.",
    benefits: ["Presupuestos", "Galería antes/después", "SEO local", "WhatsApp", "Confianza", "Formulario avanzado"],
    deliverables: ["Landing", "Servicios", "Formulario", "Galería", "SEO local", "CTA WhatsApp"],
    cta: "Captar presupuestos de limpieza",
  },
  {
    slug: "automatizacion-para-negocios-locales",
    title: "Automatización para negocios locales | IA, WhatsApp y CRM",
    description: "Automatizaciones para negocios locales que quieren responder más rápido, captar leads y ahorrar tiempo.",
    h1: "Automatización para negocios locales que quieren vender sin perder tiempo",
    eyebrow: "Negocios locales",
    pain: "Los negocios locales pierden clientes por responder tarde o no hacer seguimiento.",
    solution: "Conecto web, WhatsApp, formularios y CRM para que cada oportunidad llegue ordenada y tenga seguimiento.",
    benefits: ["Respuesta rápida", "CRM", "WhatsApp", "Recordatorios", "Menos tareas", "Más cierres"],
    deliverables: ["Flujos", "Webhook", "CRM", "Mensajes", "Notificaciones", "Panel"],
    cta: "Automatizar mi negocio",
  },
  {
    slug: "chatbot-whatsapp-para-restaurantes",
    title: "Chatbot WhatsApp para restaurantes | Reservas y pedidos",
    description: "Chatbot WhatsApp para restaurantes que responde preguntas, envía carta, gestiona reservas y capta pedidos.",
    h1: "Chatbot WhatsApp para restaurantes que quieren responder mejor y vender más",
    eyebrow: "Restaurantes + WhatsApp",
    pain: "Las preguntas repetidas sobre horario, carta, reservas y pedidos consumen tiempo y retrasan ventas.",
    solution: "Implemento un chatbot WhatsApp con flujos claros para carta, reservas, pedidos, horarios, ubicación y derivación a humano.",
    benefits: ["Atención 24/7", "Carta automática", "Reservas", "Pedidos", "Menos interrupciones", "Datos ordenados"],
    deliverables: ["Flujo conversacional", "FAQ", "Webhook", "Mensajes", "Pruebas", "Panel de leads"],
    cta: "Automatizar WhatsApp de mi restaurante",
  },
  {
    slug: "web-para-autonomos",
    title: "Web para autónomos | Marca personal y captación",
    description: "Web profesional para autónomos que necesitan vender servicios, captar leads y proyectar confianza.",
    h1: "Web para autónomos que quieren parecer una marca profesional",
    eyebrow: "Autónomos",
    pain: "Si vendes servicios y tu presencia digital no transmite confianza, compites solo por precio.",
    solution: "Construyo una web personal/profesional con oferta clara, servicios, prueba social, SEO y formulario de captación.",
    benefits: ["Marca personal", "Servicios claros", "Formulario", "SEO", "Confianza", "WhatsApp"],
    deliverables: ["Home", "Sobre mí", "Servicios", "Contacto", "SEO", "CTA"],
    cta: "Crear mi web profesional",
  },
];

export const localPages: SeoPage[] = [
  {
    slug: "diseno-web-premium-barcelona",
    title: "Diseño web premium en Barcelona | Andrés Fabián Rendón",
    description: "Diseño web premium en Barcelona para negocios que quieren captar clientes, mejorar imagen y automatizar procesos.",
    h1: "Diseño web premium en Barcelona para negocios que quieren destacar",
    eyebrow: "Barcelona",
    pain: "Barcelona está llena de negocios buenos con presencia digital débil, lenta o poco diferenciada.",
    solution: "Creo webs premium enfocadas en conversión, SEO local y automatización para que tu negocio compita con más fuerza.",
    benefits: ["SEO Barcelona", "Diseño premium", "Mobile-first", "Captación", "WhatsApp", "Automatización"],
    deliverables: ["Estrategia", "Web", "SEO", "Formulario", "Analytics", "Deploy"],
    cta: "Solicitar auditoría en Barcelona",
  },
  {
    slug: "automatizacion-ia-barcelona",
    title: "Automatización IA en Barcelona | Web, WhatsApp y CRM",
    description: "Automatización con IA en Barcelona para negocios que quieren responder más rápido, captar leads y ahorrar tiempo.",
    h1: "Automatización IA en Barcelona para negocios que quieren crecer",
    eyebrow: "IA Barcelona",
    pain: "La mayoría de negocios pierde oportunidades porque todo depende de respuestas manuales y seguimiento improvisado.",
    solution: "Implemento automatizaciones con IA, WhatsApp, webhooks y CRM para ordenar tu captación comercial.",
    benefits: ["IA", "WhatsApp", "CRM", "Leads", "Seguimiento", "Ahorro de tiempo"],
    deliverables: ["Mapa de procesos", "Automatización", "Webhook", "Mensajes", "Dashboard", "Pruebas"],
    cta: "Automatizar mi negocio en Barcelona",
  },
  {
    slug: "seo-local-para-negocios-barcelona",
    title: "SEO local para negocios en Barcelona",
    description: "SEO local para negocios en Barcelona que quieren aparecer en Google por servicios, barrios y búsquedas comerciales.",
    h1: "SEO local para negocios en Barcelona que quieren ser encontrados",
    eyebrow: "SEO local Barcelona",
    pain: "Si no apareces en búsquedas locales, la competencia captura la demanda antes que tú.",
    solution: "Creo arquitectura SEO local con páginas por servicio, ciudad, contenido, schema y medición de resultados.",
    benefits: ["Google", "Páginas locales", "Schema", "Sitemap", "Contenido", "Conversión"],
    deliverables: ["Keyword map", "Páginas SEO", "Metadata", "Schema", "Sitemap", "Plan de contenido"],
    cta: "Revisar mi SEO local",
  },
  {
    slug: "chatbot-whatsapp-empresas-barcelona",
    title: "Chatbot WhatsApp para empresas en Barcelona",
    description: "Chatbots WhatsApp para empresas en Barcelona que quieren responder más rápido, captar datos y automatizar seguimiento.",
    h1: "Chatbot WhatsApp para empresas en Barcelona que quieren captar y atender mejor",
    eyebrow: "WhatsApp Barcelona",
    pain: "Responder tarde en WhatsApp reduce reservas, presupuestos y confianza, especialmente cuando el cliente compara varias opciones.",
    solution: "Diseño flujos WhatsApp con IA, formularios, derivación a humano y registro de leads en CRM para empresas locales.",
    benefits: ["Respuesta rápida", "Captación", "FAQ", "Derivación", "CRM", "Seguimiento"],
    deliverables: ["Mapa de conversación", "Mensajes", "Webhook", "Integración CRM", "Pruebas", "Manual"],
    cta: "Crear mi chatbot WhatsApp",
  },
  {
    slug: "web-para-restaurantes-barcelona",
    title: "Web para restaurantes en Barcelona | Carta, reservas y SEO",
    description: "Web para restaurantes en Barcelona con carta digital, reservas, pedidos, reseñas, Google Maps y SEO local.",
    h1: "Web para restaurantes en Barcelona que necesitan más reservas y pedidos",
    eyebrow: "Restaurantes Barcelona",
    pain: "En una ciudad competitiva, una web lenta o poco clara hace que el cliente elija otro restaurante.",
    solution: "Creo webs premium para restaurantes con carta digital, reservas, WhatsApp, ubicación, reseñas y SEO local por intención comercial.",
    benefits: ["Carta digital", "Reservas", "Pedidos", "SEO Barcelona", "Mobile-first", "Analítica"],
    deliverables: ["Home", "Carta", "Reservas", "SEO", "CTA WhatsApp", "Deploy"],
    cta: "Auditar mi restaurante",
  },
  {
    slug: "web-para-barberias-barcelona",
    title: "Web para barberías en Barcelona | Reservas, QR y SEO",
    description: "Web para barberías en Barcelona con reservas, servicios, barberos, QR, WhatsApp y SEO local.",
    h1: "Web para barberías en Barcelona que quieren llenar mejor la agenda",
    eyebrow: "Barberías Barcelona",
    pain: "Depender solo de Instagram limita la captación y deja reservas sin ordenar.",
    solution: "Construyo webs para barberías con reservas, servicios, QR, WhatsApp, reseñas, Google Maps y páginas SEO locales.",
    benefits: ["Reservas", "QR", "SEO local", "Servicios", "WhatsApp", "Confianza"],
    deliverables: ["Landing", "Agenda", "Servicios", "SEO", "QR", "Analítica"],
    cta: "Crear sistema para mi barbería",
  },
];

export const blogPosts = [
  {
    slug: "como-una-web-premium-puede-captar-mas-clientes",
    title: "Cómo una web premium puede captar más clientes para un negocio local",
    description: "Guía práctica para convertir una web en una máquina de confianza, SEO y leads.",
    date: "2026-05-13",
    reading: "6 min",
  },
  {
    slug: "automatizar-whatsapp-en-negocios-locales",
    title: "Cómo automatizar WhatsApp en negocios locales sin perder trato humano",
    description: "Ideas para responder rápido, filtrar leads y agendar clientes usando IA y automatizaciones.",
    date: "2026-05-13",
    reading: "7 min",
  },
  {
    slug: "seo-local-para-barberias-restaurantes-y-autonomos",
    title: "SEO local para barberías, restaurantes y autónomos: qué páginas crear primero",
    description: "Mapa inicial de páginas SEO para negocios locales que quieren captar demanda desde Google.",
    date: "2026-05-13",
    reading: "8 min",
  },
];

export const allSeoPages = [
  ...services.map((p) => ({ ...p, group: "servicios", href: `/servicios/${p.slug}` })),
  ...niches.map((p) => ({ ...p, group: "nichos", href: `/nichos/${p.slug}` })),
  ...localPages.map((p) => ({ ...p, group: "barcelona", href: `/barcelona/${p.slug}` })),
];
